// Generated by CoffeeScript 1.9.2
(function($) {
  return $(function() {
    var _questionNumber;
    _questionNumber = 1;
    return $('.accessibleAccordion > li').each(function(i, e) {
      var _a, _accessibleText, _answerOrQuestion, _attrs, _isAnswer, _li;
      _a = $('<a/>');
      _li = $(e);
      _isAnswer = _li.is('.answer');
      _accessibleText = _li.data('accessibleText') || _li.text();
      if (_accessibleText != null) {
        _answerOrQuestion = _isAnswer ? "Resposta da pergunta " + (_questionNumber++) + ": " : "Pergunta " + _questionNumber + ": ";
        _attrs = {
          href: '#',
          onclick: 'return false',
          title: "" + _answerOrQuestion + _accessibleText,
          "class": 'accessibleLink'
        };
        _a.attr(_attrs);
        _a.html('&nbsp;');
        _li.on('click', function() {
          return _li.next('.answer').toggle();
        });
        _a.on('focus', function() {
          _li.addClass('focused');
          return _li.next('.answer').show();
        });
        _a.on('blur', function() {
          return _li.removeClass('focused');
        });
        return _li.prepend(_a);
      }
    }).filter('.answer').hide();
  });
})(jQuery);
